# Generated by Django 2.2.3 on 2019-07-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_videos_location_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_location',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
