# Generated by Django 2.2.3 on 2019-07-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190722_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_location',
            name='comment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
