# Generated by Django 2.2.3 on 2019-07-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_videos_location_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_location',
            name='skater',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
