# Generated by Django 2.2.3 on 2019-07-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_videos_location_skater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos_location',
            name='link',
            field=models.CharField(max_length=100000),
        ),
    ]
